# This is a basic workflow to help you get started with Actions

name: MD to Html

# Controls when the action will run. 
on:
  pull_request:
    branches:
    - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # List of files changed in PR
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # Enable listing of files matching each filter.
          # Paths to files will be available in `${FILTER_NAME}_files` output variable.
          # Paths will be formatted as JSON array
          list-files: json

          # In this example all changed files are passed to the following action to do
          # some custom processing.
          filters: |
            changed:
              - '**/*.md'
              - '**/*.html'
              - '**/*.jpg'
              - '**/*.png'
      - name: Display file names
        run: |
          echo Displaying List of changed Files
          echo ${{ steps.filter.outputs.changed_files }}
