# This is a basic workflow to help you get started with Actions

name: MD to Html

# Controls when the action will run.
on:
  pull_request:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # List of files changed in PR

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: npm install

      - name: Get Changed Files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          # Enable listing of files matching each filter.
          # Paths to files will be available in `${FILTER_NAME}_files` output variable.
          # Paths will be formatted as JSON array
          list-files: json

          # In this example all changed files are passed to the following action to do
          # some custom processing.
          filters: |
            changed:
              - 'src/**/*.md'
              - 'src/**/*.html'
              - 'src/**/*.jpg'
              - 'src/**/*.png'
              - 'src/**/*.js'

      - name: HTMLs to Deploy
        id: htmls
        run: |
          echo Displaying List of changed Files
          echo ${{ steps.filter.outputs.changed_files }}
          node src/index.js ${{ steps.filter.outputs.changed_files }}

      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: |
            az storage blob upload-batch -d '$web' -s "src/rendered/" --destination-path 'promos/utsav' --connection-string ${{ secrets.STORAGE_CONNECTION_STRING }}

#       - name: Deploy
#         uses: bacongobbler/azure-blob-storage-upload@779a18b594a1a7cf5412645e06c856324a8b01e5
#         id: deploy
#         with:
#           source_dir: "src/rendered/"
#           container_name: '$web'
#           extra_args: '--destination-path promos/utsav'
#           connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
#         run: |
#           echo Displaying Output
#           echo ${{ steps.htmls.outputs.parsedHtmls }}

